### PR TITLE
Upgrade linq2db to version 3.1.1

### PR DESCRIPTION
**Pull request by sfadeev**
After upgrading `linq2db` to version 3.1.1 in project that used LinqToDB.Identity compiled for `linq2db` version 2.x getting error due to changed signature of method `LinqToDB.DataExtensions.Insert`.

```
System.MissingMethodException: Method not found: 'Int32 LinqToDB.DataExtensions.Insert(LinqToDB.IDataContext, System.__Canon, System.String, System.String, System.String)'.
    at LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj)
   at LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Identity.UserStore`7.CreateAsync(DataConnection db, TUser user, CancellationToken cancellationToken)
   at LinqToDB.Identity.UserStore`7.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
```

Recompiled for new signature of `Insert` method of linq2db version 3.1.1, fixed tests.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/linq2db/LinqToDB.Identity?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/LinqToDB.Identity?pullRequest=22) before we can accept your contribution.<br/><br/>:x: sfadeev [sign now](https://cla.dotnetfoundation.org/linq2db/LinqToDB.Identity?pullRequest=22)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/LinqToDB.Identity?pullRequest=22) it.</sub>

**Comment by MaceWindu** [comment]
@ili, @sdanyliv what we should do about this and identity server projects? They definitely doesn't get enough love from us :)

maybe move them main repo?

**Comment by sfadeev** [comment]
Good day!
Is there any chance to release new nuget packages for LinqToDB.Identity with updated linq2db?
Please let me know if you need some help :)
Thank you!

**Comment by MaceWindu** [comment]
@sfadeev we will address this this week.
@GonzoSpire you wanted new task :)

**Comment by MaceWindu** [comment]
@GonzoSpire let's make quick release of 3.0.0 version of nuget to unblock @sfadeev and then cleanup/automate this repo

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
